// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PHMIS.Infrastructure.Context;

#nullable disable

namespace PHMIS.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250910155844_AddLabTestSeed")]
    partial class AddLabTestSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("PHMIS.Domain.Entities.Laboratory.LabTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LabTestGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LabTestGroupId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Price")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LabTestGroupId");

                    b.HasIndex("LabTestGroupId1");

                    b.ToTable("LabTests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Fasting blood glucose",
                            IsActive = true,
                            LabTestGroupId = 1,
                            Name = "Glucose",
                            Price = 10
                        },
                        new
                        {
                            Id = 2,
                            Description = "Total Cholesterol, HDL, LDL, Triglycerides",
                            IsActive = true,
                            LabTestGroupId = 1,
                            Name = "Lipid Profile",
                            Price = 25
                        },
                        new
                        {
                            Id = 3,
                            Description = "Complete Blood Count",
                            IsActive = true,
                            LabTestGroupId = 2,
                            Name = "CBC",
                            Price = 20
                        },
                        new
                        {
                            Id = 4,
                            Description = "Microbiology culture",
                            IsActive = true,
                            LabTestGroupId = 3,
                            Name = "Urine Culture",
                            Price = 30
                        });
                });

            modelBuilder.Entity("PHMIS.Domain.Entities.Laboratory.LabTestGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short?>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LabTestGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Chemistry tests",
                            Name = "Chemistry",
                            SortOrder = (short)1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Blood tests",
                            Name = "Hematology",
                            SortOrder = (short)2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Microbiology tests",
                            Name = "Microbiology",
                            SortOrder = (short)3
                        });
                });

            modelBuilder.Entity("PHMIS.Domain.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St, Springfield",
                            DateOfBirth = new DateTime(1985, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            Gender = "Male",
                            LastName = "Doe",
                            PhoneNumber = "555-1234"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Elm St, Springfield",
                            DateOfBirth = new DateTime(1990, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            Gender = "Female",
                            LastName = "Smith",
                            PhoneNumber = "555-5678"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Oak St, Springfield",
                            DateOfBirth = new DateTime(1978, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alex.johnson@example.com",
                            FirstName = "Alex",
                            Gender = "Other",
                            LastName = "Johnson",
                            PhoneNumber = "555-9012"
                        });
                });

            modelBuilder.Entity("PHMIS.Domain.Entities.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("PHMIS.Domain.Entities.Laboratory.LabTest", b =>
                {
                    b.HasOne("PHMIS.Domain.Entities.Laboratory.LabTestGroup", "LabTestGroup")
                        .WithMany()
                        .HasForeignKey("LabTestGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PHMIS.Domain.Entities.Laboratory.LabTestGroup", null)
                        .WithMany("LabTests")
                        .HasForeignKey("LabTestGroupId1");

                    b.Navigation("LabTestGroup");
                });

            modelBuilder.Entity("PHMIS.Domain.Entities.Laboratory.LabTestGroup", b =>
                {
                    b.Navigation("LabTests");
                });
#pragma warning restore 612, 618
        }
    }
}
